const assert = require('assert').strict;
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.resolve(__dirname, '../sidepanel/sidepanel.html'), 'utf8');
const script = fs.readFileSync(path.resolve(__dirname, '../sidepanel/sidepanel.js'), 'utf8');
const i18n = fs.readFileSync(path.resolve(__dirname, '../lib/i18n.js'), 'utf8');

assert.match(html, /data-i18n-aria-label="open_more"/);
assert.match(html, /id="theme-setting"/);
assert.match(html, /id="language-setting"/);
assert.match(html, /id="replay-tutorial"/);
assert.match(script, /ReMarkI18n\.setLocale\(normalized\)/);
assert.match(script, /updateSettings\(\{ language: preference \}\)/);
assert.match(script, /normalizeThemePreference\(preference\)/);
assert.match(script, /updateSettings\(\{ theme: preference \}\)/);
assert.match(script, /window\.matchMedia\?\.\('\(prefers-color-scheme: dark\)'\)/);
assert.match(script, /if \(systemThemeQuery\?\.addEventListener\) systemThemeQuery\.addEventListener\('change', onSystemThemeChange\)/);
assert.match(script, /document\.documentElement\.dataset\.theme = resolved/);
assert.match(i18n, /more: 'More'/);
assert.match(i18n, /language_system: 'System default'/);
assert.match(i18n, /appearance: 'Appearance'/);
assert.match(i18n, /appearance_system: 'System default'/);
assert.match(i18n, /appearance_light: 'Light'/);
assert.match(i18n, /appearance_dark: 'Dark'/);
const sourceSummary = script.slice(script.indexOf("if (inSource)"), script.indexOf("} else {", script.indexOf("if (inSource)")));
assert.doesNotMatch(sourceSummary, /source_summary/);
assert.match(sourceSummary, /host\(sourceUrl\) \|\| sourceUrl/);

console.log('more-panel.test.js: all assertions passed');
const moreHeader = html.slice(html.indexOf('id="panel-settings"'), html.indexOf('class="language-section"'));
assert.doesNotMatch(moreHeader, /<h1/);
assert.match(script, /viewIdentity\.hidden = true/);
assert.match(script, /viewIdentity\.hidden = false/);
const css = fs.readFileSync(path.resolve(__dirname, '../sidepanel/sidepanel.css'), 'utf8');
assert.match(css, /\.app-container\.is-more-open #panel-clips \{ display: none !important; \}/);
assert.match(css, /\.settings-panel \{ position: absolute; z-index: 20; inset: 0;/);
assert.match(css, /:root\[data-theme='dark'\]\s*\{/);
assert.match(css, /:root\[data-theme='dark'\][\s\S]*?color-scheme: dark/);
assert.match(css, /\.appearance-section,[\s\S]*?\.language-section\s*\{/);
assert.match(css, /:root\[data-theme='dark'\][\s\S]*?--selection-tray-bg: rgba\(37, 40, 46, \.98\)/);
assert.match(css, /:root\[data-theme='dark'\][\s\S]*?--primary-action: #f0cf57/);
assert.match(css, /\.selection-tray\s*\{[\s\S]*?background: var\(--selection-tray-bg\)/);
assert.match(css, /\.selection-export:hover,[\s\S]*?background: var\(--control-hover-bg\)/);
assert.match(css, /\.backup-action\s*\{[\s\S]*?background: var\(--primary-action\)[\s\S]*?color: var\(--primary-action-ink\)/);
assert.match(css, /\.feedback-submit\s*\{[\s\S]*?background: var\(--primary-action\)[\s\S]*?color: var\(--primary-action-ink\)/);
assert.match(css, /\.backup-action:hover\s*\{[\s\S]*?background: var\(--primary-action-hover\)/);
assert.match(css, /\.feedback-submit:hover\s*\{[\s\S]*?background: var\(--primary-action-hover\)/);
assert.match(script, /appContainer\.classList\.add\('is-more-open'\)/);
assert.match(script, /appContainer\.classList\.remove\('is-more-open'\)/);
const sourceView = script.slice(script.indexOf('if (inSource)'), script.indexOf("let previous = ''"));
assert.match(sourceView, /source-collection-source-row/);
assert.match(sourceView, /source-collection-url/);
assert.match(sourceView, /source-collection-favicon/);
assert.match(sourceView, /source-collection-page-title/);
assert.match(sourceView, /const sourceTitle = sourceRows\[0\]\?\.title/);
assert.doesNotMatch(sourceView, /subtitle\.textContent = title/);
assert.match(script, /viewIdentity\.hidden = false/);
assert.match(script, /settingsOpenButton\.hidden = inSource/);
assert.match(script, /const sourceControl = sourceUrl === null/);
assert.match(script, /const footer = sourceUrl === null[\s\S]*<footer class="mark-footer">\$\{sourceControl\}<time class="mark-created"[\s\S]*: '';/);
assert.doesNotMatch(html, /class="search-icon"/);
assert.doesNotMatch(html, /class="search-kbd"/);
assert.match(script, /search\.placeholder = t\('search_placeholder'\)/);
assert.match(script, /if \(inSource\) \{[\s\S]*setViewTitle\(t\('source_marks'\), sourceRows\.length\)/);
assert.doesNotMatch(html, /id="view-count"/);
assert.match(i18n, /timeline: 'Timeline'/);
assert.match(i18n, /source_marks: 'Collection'/);
assert.match(i18n, /search_placeholder: 'Search Marks, notes, sources, or timestamps'/);
console.log('more-panel.test.js: all assertions passed');

assert.match(html, /<section class="shortcuts-section" aria-labelledby="shortcuts-heading">/);
assert.match(html, /data-i18n="core_shortcuts"/);
assert.match(html, /data-i18n="shortcut_mark_text"/);
assert.match(html, /data-i18n="shortcut_mark_video"/);
assert.match(html, /data-i18n="shortcut_delete"/);
assert.match(i18n, /core_shortcuts: '核心快捷键'/);
assert.match(i18n, /core_shortcuts: 'Core shortcuts'/);
assert.match(i18n, /shortcut_mark_video: 'Mark video moment'/);
assert.match(css, /\.shortcuts-section \{[\s\S]*border-bottom: 1px solid var\(--line\);/);
assert.match(css, /\.shortcut-row \{[\s\S]*justify-content: space-between;/);
assert.match(css, /\.shortcut-row kbd \{[\s\S]*font-family: ui-monospace/);
console.log('core-shortcuts-panel assertions passed');

assert.match(html, /data-i18n="shortcut_mark_text_note"/);
assert.match(html, /data-i18n="shortcut_edit_note"/);
assert.match(html, /data-i18n="shortcut_toggle_selection"/);
assert.match(html, /data-i18n="shortcut_range_selection"/);
assert.match(html, /data-shortcut-modifier/);
assert.doesNotMatch(html.slice(html.indexOf('shortcuts-section'), html.indexOf('help-section')), /data-i18n="shortcut_search"|data-i18n="shortcut_undo"/);
assert.match(i18n, /shortcut_mark_text_note: '划线并添加笔记'/);
assert.match(i18n, /shortcut_mark_text_note: 'Mark text and add a note'/);
assert.match(i18n, /shortcut_toggle_selection: 'Add or remove Marks from selection'/);
assert.match(script, /function applyShortcutModifierLabels\(\) \{[\s\S]*isMacPlatform\(\) \? '⌘' : 'Ctrl'/);
assert.match(script, /ReMarkI18n\.apply\(\);[\s\S]*applyShortcutModifierLabels\(\);/);
console.log('core-shortcuts-platform assertions passed');

const content = fs.readFileSync(path.resolve(__dirname, '../content/content.js'), 'utf8');
assert.match(html, /data-i18n="shortcut_mark_video_note"/);
assert.match(i18n, /shortcut_mark_video_note: '标记当前视频时刻并添加笔记'/);
assert.match(i18n, /shortcut_mark_video_note: 'Mark video moment and add a note'/);
const videoShortcut = content.slice(content.indexOf('function onVideoMarkKeydown'), content.indexOf('function getVideoTimelineBar'));
assert.match(videoShortcut, /recordVideoMark\(\{ withNote: e\.shiftKey \}\)/);
console.log('video-note-shortcut assertions passed');
