const assert = require('assert').strict;
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.resolve(__dirname, '../sidepanel/sidepanel.html'), 'utf8');
const script = fs.readFileSync(path.resolve(__dirname, '../sidepanel/sidepanel.js'), 'utf8');
const i18n = fs.readFileSync(path.resolve(__dirname, '../lib/i18n.js'), 'utf8');

assert.match(html, /data-i18n-aria-label="open_more"/);
assert.match(html, /id="language-setting"/);
assert.match(html, /id="replay-tutorial"/);
assert.match(script, /ReMarkI18n\.setLocale\(normalized\)/);
assert.match(script, /updateSettings\(\{ language: preference \}\)/);
assert.match(i18n, /more: 'More'/);
assert.match(i18n, /language_system: 'System default'/);
const sourceSummary = script.slice(script.indexOf("if (inSource)"), script.indexOf("} else {", script.indexOf("if (inSource)")));
assert.doesNotMatch(sourceSummary, /source_summary/);
assert.match(sourceSummary, /host\(sourceUrl\) \|\| sourceUrl/);

console.log('more-panel.test.js: all assertions passed');
const moreHeader = html.slice(html.indexOf('id="panel-settings"'), html.indexOf('class="language-section"'));
assert.doesNotMatch(moreHeader, /<h1/);
assert.match(script, /viewIdentity\.hidden = true/);
assert.match(script, /viewIdentity\.hidden = false/);
const css = fs.readFileSync(path.resolve(__dirname, '../sidepanel/sidepanel.css'), 'utf8');
assert.match(css, /\.app-container\.is-more-open #panel-clips \{ display: none !important; \}/);
assert.match(css, /\.settings-panel \{ position: absolute; z-index: 20; inset: 0;/);
assert.match(script, /appContainer\.classList\.add\('is-more-open'\)/);
assert.match(script, /appContainer\.classList\.remove\('is-more-open'\)/);
const sourceView = script.slice(script.indexOf('if (inSource)'), script.indexOf("let previous = ''"));
assert.match(sourceView, /source-collection-source-row/);
assert.match(sourceView, /source-collection-url/);
assert.match(sourceView, /source-collection-favicon/);
assert.match(sourceView, /source-collection-page-title/);
assert.match(sourceView, /const sourceTitle = sourceRows\[0\]\?\.title/);
assert.doesNotMatch(sourceView, /subtitle\.textContent = title/);
assert.match(script, /viewIdentity\.hidden = false/);
assert.match(script, /settingsOpenButton\.hidden = inSource/);
assert.match(script, /const sourceControl = sourceUrl === null/);
assert.match(script, /<footer class="mark-footer">\$\{sourceControl \|\| '<span class="mark-source-slot"><\/span>'\}<time class="mark-created"/);
assert.doesNotMatch(html, /class="search-icon"/);
assert.doesNotMatch(html, /class="search-kbd"/);
assert.match(script, /search\.placeholder = t\('search_placeholder'\)/);
assert.match(script, /if \(inSource\) \{[\s\S]*setViewTitle\(t\('source_marks'\), sourceRows\.length\)/);
assert.doesNotMatch(html, /id="view-count"/);
assert.match(i18n, /timeline: 'Timeline'/);
assert.match(i18n, /source_marks: 'Collection'/);
assert.match(i18n, /search_placeholder: 'Search Marks, notes, sources, or timestamps'/);
console.log('more-panel.test.js: all assertions passed');
