const assert = require('assert').strict;
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.resolve(__dirname, '../sidepanel/sidepanel.html'), 'utf8');
const script = fs.readFileSync(path.resolve(__dirname, '../sidepanel/sidepanel.js'), 'utf8');
const i18n = fs.readFileSync(path.resolve(__dirname, '../lib/i18n.js'), 'utf8');
const storage = fs.readFileSync(path.resolve(__dirname, '../lib/storage.js'), 'utf8');

assert.match(html, /data-i18n-aria-label="open_more"/);
assert.match(html, /id="theme-setting"/);
assert.match(html, /class="mark-appearance-section"/);
assert.match(html, /class="mark-color-picker" role="radiogroup"/);
['#FF5500', '#F5A623', '#FF5C5C', '#3873B2', '#F5C542', '#468282'].forEach((color) => assert.match(html, new RegExp(`data-mark-color="${color}"`)));
assert.match(html, /id="language-setting"/);
assert.match(html, /id="replay-tutorial"/);
assert.match(script, /ReMarkI18n\.setLocale\(normalized\)/);
assert.match(script, /updateSettings\(\{ language: preference \}\)/);
assert.match(script, /normalizeThemePreference\(preference\)/);
assert.match(script, /updateSettings\(\{ theme: preference \}\)/);
assert.match(script, /const markColorSwatches = \[\.\.\.document\.querySelectorAll\('\.mark-color-swatch'\)\]/);
assert.match(script, /function applyMarkColorPreference\(color\)/);
assert.match(script, /updateSettings\(\{ defaultColor: color \}\)/);
assert.match(script, /syncMarkColorToOpenTabs\(settings\.defaultColor\)/);
assert.match(script, /window\.matchMedia\?\.\('\(prefers-color-scheme: dark\)'\)/);
assert.match(script, /if \(systemThemeQuery\?\.addEventListener\) systemThemeQuery\.addEventListener\('change', onSystemThemeChange\)/);
assert.match(script, /document\.documentElement\.dataset\.theme = resolved/);
assert.match(i18n, /more: 'More'/);
assert.match(i18n, /language_system: 'System default'/);
assert.match(i18n, /appearance: 'Appearance'/);
assert.match(i18n, /appearance_system: 'System default'/);
assert.match(i18n, /appearance_light: 'Light'/);
assert.match(i18n, /appearance_dark: 'Dark'/);
assert.match(i18n, /mark_appearance: 'Mark Appearance'/);
assert.match(i18n, /mark_color_trail_orange: 'Trail Orange'/);
assert.match(i18n, /mark_color_beacon_yellow: 'Beacon Yellow'/);
assert.match(i18n, /mark_color_harbor_mist: 'Harbor Mist'/);
const sourceSummary = script.slice(script.indexOf("if (inSource)"), script.indexOf("} else {", script.indexOf("if (inSource)")));
assert.doesNotMatch(sourceSummary, /source_summary/);
assert.match(sourceSummary, /host\(sourceUrl\) \|\| sourceUrl/);

console.log('more-panel.test.js: all assertions passed');
const moreHeader = html.slice(html.indexOf('id="panel-settings"'), html.indexOf('class="language-section"'));
assert.doesNotMatch(moreHeader, /<h1/);
assert.match(script, /viewIdentity\.hidden = true/);
assert.match(script, /viewIdentity\.hidden = false/);
const css = fs.readFileSync(path.resolve(__dirname, '../sidepanel/sidepanel.css'), 'utf8');
assert.match(css, /\.app-container\.is-more-open #panel-clips \{ display: none !important; \}/);
assert.match(css, /\.settings-panel \{ position: absolute; z-index: 20; inset: 0;/);
assert.match(css, /:root\[data-theme='dark'\]\s*\{/);
assert.match(css, /:root\[data-theme='dark'\][\s\S]*?color-scheme: dark/);
assert.match(css, /\.appearance-section,[\s\S]*?\.language-section\s*\{/);
assert.match(css, /--mark-color: #ff5500/);
assert.match(css, /\.mark-color-picker \{/);
assert.match(css, /\.mark-color-swatch\[aria-checked='true'\] \{/);
assert.match(css, /\.mark-quote \{[\s\S]*?color: var\(--mark-color\)/);
assert.match(css, /\.mark-quote--video \{[\s\S]*?background: var\(--mark-color\)/);
assert.match(css, /:root\[data-theme='dark'\][\s\S]*?--selection-tray-bg: rgba\(37, 40, 46, \.98\)/);
assert.match(css, /--gold: #ff5500;[\s\S]*?--gold-soft: rgba\(255, 85, 0, \.10\)/);
assert.match(css, /:root\[data-theme='dark'\][\s\S]*?--primary-action: #ff5500/);
assert.match(css, /:root\[data-theme='dark'\][\s\S]*?--focus-ring: rgba\(255, 85, 0, \.72\)/);
assert.match(storage, /BRAND_COLOR: '#FF5500'/);
assert.match(storage, /MARK_COLOR_PRESETS: \{[\s\S]*?trail_orange: '#FF5500',[\s\S]*?beacon_yellow: '#F5C542',[\s\S]*?harbor_mist: '#468282'/);
assert.match(storage, /normalizeMarkColor\(color\)/);
assert.match(storage, /LEGACY_DEFAULT_AMBER: '#FFE066'/);
assert.match(storage, /defaultColor: '#FF5500'/);
assert.match(css, /\.selection-tray\s*\{[\s\S]*?background: var\(--selection-tray-bg\)/);
assert.match(css, /\.selection-export:hover,[\s\S]*?background: var\(--control-hover-bg\)/);
assert.match(css, /\.backup-action\s*\{[\s\S]*?background: var\(--primary-action\)[\s\S]*?color: var\(--primary-action-ink\)/);
assert.match(css, /\.feedback-submit\s*\{[\s\S]*?background: var\(--primary-action\)[\s\S]*?color: var\(--primary-action-ink\)/);
assert.match(css, /\.backup-action:hover\s*\{[\s\S]*?background: var\(--primary-action-hover\)/);
assert.match(css, /\.feedback-submit:hover\s*\{[\s\S]*?background: var\(--primary-action-hover\)/);
assert.match(script, /appContainer\.classList\.add\('is-more-open'\)/);
assert.match(script, /appContainer\.classList\.remove\('is-more-open'\)/);
const sourceView = script.slice(script.indexOf('if (inSource)'), script.indexOf("let previous = ''"));
assert.match(sourceView, /source-collection-source-row/);
assert.match(sourceView, /source-collection-url/);
assert.match(sourceView, /source-collection-favicon/);
assert.match(sourceView, /source-collection-page-title/);
assert.match(sourceView, /const sourceTitle = sourceRows\[0\]\?\.title/);
assert.doesNotMatch(sourceView, /subtitle\.textContent = title/);
assert.match(script, /viewIdentity\.hidden = false/);
assert.match(script, /settingsOpenButton\.hidden = inSource/);
assert.match(script, /const sourceControl = sourceUrl === null/);
assert.match(script, /const footer = sourceUrl === null[\s\S]*<footer class="mark-footer">\$\{sourceControl\}<time class="mark-created"[\s\S]*: '';/);
assert.doesNotMatch(html, /class="search-icon"/);
assert.doesNotMatch(html, /class="search-kbd"/);
assert.match(script, /search\.placeholder = t\('search_placeholder'\)/);
assert.match(script, /if \(inSource\) \{[\s\S]*setViewTitle\(t\('timeline'\), sourceRows\.length, false\)/);
assert.match(script, /source-collection-count.*· \$\{esc\(countLabel\)\}/);
assert.match(script, /timelineControls\.hidden = inSource/);
assert.doesNotMatch(html, /id="view-count"/);
assert.match(i18n, /timeline: 'Timeline'/);
assert.match(i18n, /source_marks: 'Collection'/);
assert.match(i18n, /search_placeholder: 'Search Marks, notes, sources, or timestamps'/);
console.log('more-panel.test.js: all assertions passed');

assert.match(html, /<section class="shortcuts-section" aria-labelledby="shortcuts-heading">/);
assert.match(html, /data-i18n="core_shortcuts"/);
assert.match(html, /data-i18n="shortcut_mark_text"/);
assert.match(html, /data-i18n="shortcut_mark_video"/);
assert.match(html, /data-i18n="shortcut_delete"/);
assert.match(i18n, /core_shortcuts: '核心快捷键'/);
assert.match(i18n, /core_shortcuts: 'Core shortcuts'/);
assert.match(i18n, /shortcut_mark_video: 'Mark video moment'/);
assert.match(css, /\.shortcuts-section \{[\s\S]*border-bottom: 1px solid var\(--line\);/);
assert.match(css, /\.shortcut-row \{[\s\S]*justify-content: space-between;/);
assert.match(css, /\.shortcut-row kbd \{[\s\S]*font-family: ui-monospace/);
console.log('core-shortcuts-panel assertions passed');

assert.match(html, /data-i18n="shortcut_mark_text_note"/);
assert.match(html, /data-i18n="shortcut_edit_note"/);
assert.match(html, /data-i18n="shortcut_toggle_selection"/);
assert.match(html, /data-i18n="shortcut_range_selection"/);
assert.match(html, /data-shortcut-modifier/);
assert.doesNotMatch(html.slice(html.indexOf('shortcuts-section'), html.indexOf('help-section')), /data-i18n="shortcut_search"|data-i18n="shortcut_undo"/);
assert.match(i18n, /shortcut_mark_text_note: '划线并添加笔记'/);
assert.match(i18n, /shortcut_mark_text_note: 'Mark text and add a note'/);
assert.match(i18n, /shortcut_toggle_selection: 'Add or remove Marks from selection'/);
assert.match(script, /function applyShortcutModifierLabels\(\) \{[\s\S]*isMacPlatform\(\) \? '⌘' : 'Ctrl'/);
assert.match(script, /ReMarkI18n\.apply\(\);[\s\S]*applyShortcutModifierLabels\(\);/);
console.log('core-shortcuts-platform assertions passed');

const content = fs.readFileSync(path.resolve(__dirname, '../content/content.js'), 'utf8');
const contentCss = fs.readFileSync(path.resolve(__dirname, '../content/content.css'), 'utf8');
assert.match(content, /DEFAULT_HIGHLIGHT_COLOR = '#FF5500'/);
assert.match(content, /let activeMarkColor = DEFAULT_HIGHLIGHT_COLOR/);
assert.match(content, /function applyGlobalMarkColor\(color\)/);
assert.match(content, /style\.setProperty\('--remark-brand', activeMarkColor\)/);
assert.match(content, /msg\.action === 'APPLY_MARK_COLOR'/);
assert.match(content, /quickHighlightSelection\(activeMarkColor/);
assert.match(contentCss, /--remark-brand: rgb\(255, 85, 0\)/);
assert.match(contentCss, /--remark-brand-soft: color-mix\(in srgb, var\(--remark-brand\) 18%, transparent\)/);
assert.match(contentCss, /mark\.remark-highlight-mark \{[\s\S]*?--remark-highlight-bg: var\(--remark-brand\)[\s\S]*?background-image: linear-gradient\([\s\S]*?color: #fff[\s\S]*?box-shadow: none/);
assert.doesNotMatch(contentCss, /::selection \{/);
assert.doesNotMatch(contentCss, /::-moz-selection \{/);
assert.match(contentCss, /--remark-menu-surface: rgba\(255, 255, 255, \.98\)/);
assert.match(contentCss, /@media \(prefers-color-scheme: dark\)[\s\S]*?--remark-menu-surface: rgba\(35, 38, 45, \.98\)/);
assert.match(contentCss, /\.remark-mark-actions,[\s\S]*?\.remark-video-mark-tip \{[\s\S]*?background: var\(--remark-menu-surface\)/);
assert.match(contentCss, /\.remark-mark-action:not\(\.remark-mark-action--delete\):hover,[\s\S]*?background: var\(--remark-menu-hover\)/);
assert.match(html, /data-i18n="shortcut_mark_video_note"/);
assert.match(i18n, /shortcut_mark_video_note: '标记当前视频时刻并添加笔记'/);
assert.match(i18n, /shortcut_mark_video_note: 'Mark video moment and add a note'/);
const videoShortcut = content.slice(content.indexOf('function onVideoMarkKeydown'), content.indexOf('function getVideoTimelineBar'));
assert.match(videoShortcut, /recordVideoMark\(\{ withNote: e\.shiftKey \}\)/);
console.log('video-note-shortcut assertions passed');
