const assert = require('assert').strict;
const fs = require('fs');
const path = require('path');
const read = (file) => fs.readFileSync(path.resolve(__dirname, '..', file), 'utf8');
const content = read('content/content.js');
const sidepanel = read('sidepanel/sidepanel.js');
const background = read('background.js');
const manifest = JSON.parse(read('manifest.json'));
const i18n = read('lib/i18n.js');

assert.match(sidepanel, /async function deleteMarks\(keys = selectedKeys\)/);
assert.match(sidepanel, /Promise\.all\(highlights\.map\(\(item\) => notifySourceTabs\(item, \{ action: 'DELETE_CLIP_FROM_PAGE', clipId: item\.id \}\)\)\)/);
assert.match(sidepanel, /function clearNativeTextSelection\(\)[\s\S]*window\.getSelection/);
assert.match(sidepanel, /list\.addEventListener\('mousedown',[\s\S]*isShiftRangePointer\(event\)[\s\S]*event\.preventDefault\(\)/);
assert.match(content, /function positionVideoMarkPanel\(panel, anchor\)[\s\S]*window\.innerWidth[\s\S]*window\.innerHeight/);
assert.match(content, /positionVideoMarkPanel\(tip, tooltipAnchor\)/);
assert.doesNotMatch(read('content/content.css'), /\.remark-video-mark-card::after/);
assert.match(sidepanel, /async function notifySourceTabs[\s\S]*Promise\.all/);
assert.match(sidepanel, /action: 'RESTORE_HIGHLIGHTS'/);
assert.match(content, /function schedulePageHighlightRestore\(\)[\s\S]*DOMContentLoaded[\s\S]*\[800, 2200, 4000, 7000\]\.forEach/);
assert.match(content, /new MutationObserver\(\(\) => \{/);
assert.match(content, /observer\.disconnect\(\), 20000\)/);
assert.match(content, /function samePageUrl\(a, b\)/);
assert.match(content, /const textSegments = \[\];[\s\S]*let startIndex = text\.indexOf\(clip\.text\)[\s\S]*highlightDOMRange\(range, clip\)/);
assert.match(content, /function reportSourceUnavailable\(clipId\)[\s\S]*action: 'SOURCE_MARK_UNAVAILABLE'/);
assert.match(sidepanel, /SOURCE_MARK_UNAVAILABLE[\s\S]*source_unavailable/);
assert.match(sidepanel, /action: 'TRACK_SOURCE_NAVIGATION'/);
assert.match(background, /chrome\.webNavigation\.onErrorOccurred\.addListener/);
assert.ok(manifest.permissions.includes('webNavigation'));
assert.match(i18n, /source_unavailable: '无法找到原网页或对应内容/);
assert.match(i18n, /source_unavailable: 'The original page or marked content could not be found/);
console.log('page-sync.test.js: all assertions passed');

assert.doesNotMatch(content, /selectedHighlight/);
assert.match(content, /initialValue: item\.note \|\| ''/);
assert.match(content, /function openQuickNoteInput\(\{ rect, onSave, initialValue = '', above = false \}\)/);
assert.match(content, /input\.value = initialValue/);
assert.match(content, /function bindHighlightClick\(element, clip\)[\s\S]*showHighlightActions\(clip\.id[,)]/);
const clickHandler = content.slice(content.indexOf('function bindHighlightClick'), content.indexOf('function notifyStorageUpdated'));
assert.doesNotMatch(clickHandler, /OPEN_SIDE_PANEL/);
assert.match(content, /event\.preventDefault\(\);[\s\S]*event\.stopPropagation\(\);[\s\S]*showHighlightActions\(clip\.id[,)]/);
assert.doesNotMatch(read('content/content.css'), /remark-selected \{[\s\S]*inset 0 -2px/);
console.log('page-mark-interaction assertions passed');

assert.match(content, /if \(event\.button !== 0\) return;/);
assert.match(content, /showMarkPill\(\{ text, range: range\.cloneRange\(\), sourceUrl: getSelectionSourceUrl\(range\) \}, \{ x: event\.clientX, y: event\.clientY \}\)/);
assert.match(content, /remark-mark-pill/);
assert.match(content, /t\('unmark'\)/);
assert.match(content, /remark-mark-action--marked/);
assert.match(read('content/content.css'), /\.remark-mark-pill \{/);
assert.match(content, /async function undoPageAction\(\)[\s\S]*ReMarkStorage\.get\(ReMarkStorage\.KEYS\.UNDO\)[\s\S]*ReMarkStorage\.undoLast\(\)/);
assert.match(content, /action\.type === 'restore_clip'[\s\S]*removeClipHighlightFromDOM\(action\.id, \{ immediate: true \}\)/);
assert.match(content, /function cancelClipHighlightRemoval\(clipId\)[\s\S]*remarkRemovalPending/);
assert.match(content, /event\.key\.toLowerCase\(\) !== 'z'[\s\S]*await undoPageAction\(\)/);
console.log('page-highlight-undo assertions passed');

assert.match(content, /function attachNoteControl\(mark, clip\)[\s\S]*className = 'remark-note-control'/);
assert.match(content, /control\.addEventListener\('click'[\s\S]*openQuickNoteInput\([\s\S]*initialValue: note/);
assert.match(content, /const showNote = Boolean\(clip\.note && segment === textSegments\[0\]\)/);
assert.match(content, /async function setClipNoteIndicator\(clipId\)[\s\S]*marks\.at\(0\)/);
console.log('page-note-control assertions passed');

assert.match(sidepanel, /action: 'RESTORE_HIGHLIGHTS'[\s\S]*action: 'LOCATE_CLIP'/);
assert.match(content, /const normalizedClipText = String\(clip\.text\)\.replace\(\/\\s\+\/g, ''\)/);
assert.match(content, /originalIndexes\.push\(index\)[\s\S]*normalizedPageText\.indexOf\(normalizedClipText\)/);
console.log('sidepanel-locate-recovery assertions passed');

assert.match(sidepanel, /if \(action === 'jump' && \(event\.shiftKey \|\| event\.metaKey \|\| event\.ctrlKey\)\) \{ selectCard\(key, event\); return; \}/);
assert.match(sidepanel, /if \(action === 'jump'\) \{[\s\S]*setSelection\(\[key\], key\);[\s\S]*setActive\(key\);[\s\S]*if \(isGlyphHit\(event, control\)\) void jump\(itemFor\(key\)\);[\s\S]*return;/);
assert.match(sidepanel.slice(sidepanel.indexOf("list.addEventListener('click'", sidepanel.indexOf('function isGlyphHit')), sidepanel.indexOf("list.addEventListener('click'", sidepanel.indexOf('function isGlyphHit')) + 1400), /isGlyphHit\(event, control\)/);
assert.match(sidepanel, /const createdTime = \(value\) =>[\s\S]*hour: '2-digit'/);
assert.match(sidepanel, /feed-day-label" title="\$\{esc\(fullDate\(item\.createdAt\)\)\}/);
assert.doesNotMatch(sidepanel, /list\.addEventListener\('mouseover'/);
assert.match(sidepanel, /if \(sourceUrl !== null\) rows = rows\.filter\(\(item\) => sameUrl\(item\.url, sourceUrl\)\)/);
assert.match(sidepanel.slice(sidepanel.indexOf('function visible()'), sidepanel.indexOf('function day(value)')), /item\.title,[\s\S]*item\.url/);
assert.match(sidepanel, /pointermove[\s\S]*is-glyph-hover[\s\S]*isGlyphHit\(event, control\)/);
assert.match(content, /if \(mark\) \{[\s\S]*performLocateAnimation\(mark\)/);
assert.match(content, /mark\.scrollIntoView\(\{ behavior: 'smooth', block: 'center', inline: 'nearest' \}\)/);
console.log('viewport-mark-locate assertions passed');

assert.match(content, /function ensureHighlightActions\(clipId\)[\s\S]*remark-mark-action--mark[\s\S]*remark-mark-action--note[\s\S]*remark-mark-action--copy/);
assert.match(content, /showHighlightActions\(savedClip\.id, 2800\)/);
assert.match(content, /element\.addEventListener\('mouseenter', \(\) => scheduleHighlightActionShow\(clip\.id\)\)/);
assert.match(content, /HIGHLIGHT_ACTION_SHOW_DELAY = 350/);
assert.match(read('content/content.css'), /\.remark-mark-actions-anchor \{\n  position: relative;[\s\S]*vertical-align: bottom;/);
assert.match(read('content/content.css'), /\.remark-mark-actions \{\n  position: absolute;[\s\S]*top: calc\(100% \+ \.1em\);[\s\S]*right: -\.1em;/);
assert.match(content, /remark-mark-actions-anchor/);

assert.match(content, /async function deletePageClip\(clipId\)[\s\S]*ReMarkStorage\.pushUndo/);
assert.match(read('content/content.css'), /\.remark-mark-action::after \{[\s\S]*content: attr\(data-hint\)/);
assert.match(read('content/content.css'), /remark-mark-actions\.is-visible/);
console.log('page-highlight-actions assertions passed');
